### ISSUE TITLE
Kettle Demo Checklist

### ISSUE THREAD

**Issue by sylv256** [KettleOS/kettle#2]
# Kettle Demo Checklist
- [ ] Properly implement a `RwExLock` instead of using the current null-lock impl. of `KernelInitLock`.
- [ ] Properly implement a basic allocator for runtime kernel metadata created and used by the various subsystems (e.g. driver initialization).
- [ ] Move toward modular design.
- [ ] Work on some kind of fool-proof Rust ABI for Rust-based kernel modules.
- [ ] Create Usermode API (*not* syscall-based!).

## Description
This checklist must be fulfilled before any demos or web infrastructure is set up. We want to have something resembling stable to show to the world.
